// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef Gauge_h
#define Gauge_h
#include <FL/Fl.H>
#include <FL/Fl_Widget.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Button.H>
#include <vector>
#include <stdint.h>
#include <iostream>

class Gauge : public Fl_Widget {
public:
  Gauge(int x, int y, int size, double lower, double upper);
  void setLabel(const char *lbl);
  
  double value;
protected:
  void draw();
private:
  int size;
  int XCent, YCent;
  int needlePivotSize;
  double radius;
  std::vector<double> majorTicks;
  std::vector<double> minorTicks;
  char *label;

  double angStart, angEnd;
  double valueMin, valueMax;
  double *subRange;



};

#endif
